#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gdlib = env_modules.Clone()

module_obj = []

env_gdlib.add_source_files(module_obj, "*.cpp")
env_gdlib.add_source_files(module_obj, "src/*.cpp")

env.modules_sources += module_obj
